# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Tilgjengelige piloter"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "advarsel: kunne ikke åpne spesialfil"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "for skriving"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "kan ikke stryke vakthunden"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr "advarsel: kunne ikke gjøre autopilotprosessen i sanntid"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "server / klient kjører også _slowly_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "sensorene går for sakte"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotrutinen går for sakte"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "servo går for sakte"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-biblioteket ble ikke oppdaget. Installer det"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Bruker innstillingsfil"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "FEIL: Ingen IMU oppdaget"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEIL: IMU Init mislyktes, ingen treghetsdata tilgjengelig"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "advarsel, klarte ikke å gjøre imu-prosessen i sanntid"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "laget imu-prosessen i sanntid"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "sette innledende gyro bias"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "imu-prosessen klarte ikke å holde tiden"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "mislyktes i å lese IMU!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "imu rate satt til rate"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "for høy stående gyroforstyrrelse, tilbakestiller sensorer"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "kompass utenfor rekkevidde, tilbakestilles"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "advarsel, klarte ikke å gjøre kalibreringsprosessen annen"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"advarsel, klarte ikke å gjøre kalibreringsprosessen inaktiv, og prøvde å "
"nekte"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "advarsel, mislyktes i å nekte kalibreringsprosessen"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "kalibrering lastet, starter"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "mislykket importkalibreringstilpasning"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "accel-verdiene er ugyldige"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "overløp i pypilot udp-stikkontakt"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "overløp i pypilotkontakt"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "kunne ikke sende udp-pakken"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "pypilot-kontakten kunne ikke sendes til"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "socket send tok for lang tid!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "stikkontaktfeil"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "unntak for pypilotuttak"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"faller tilbake til python ikke-blokkerende stikkontakt, vil forbruke mer CPU"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "socket sende feil i serveren flush"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "feil ved mottak av data"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"kunne ikke laste vitenskapelig bibliotek, kan ikke utføre "
"kalibreringsoppdatering!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "advarsel, registrere eksisterende verdi:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "mislyktes i å lese konfigurasjonsfilen:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "mislyktes i å skrive konfigurasjonsfil:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Unntak for å skrive konfigurasjonsfil:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "ugyldig melding fra server:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "advarsel, har pypilot-klienten allerede tilkobling"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "koble mislyktes i"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "kunne ikke koble til"

#: pypilot/client.py:460
msgid "usage"
msgstr "bruk"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "angi verten eller ip-adressen"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "skrive ut info om hver verditype"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "kontinuerlig klokke"

#: pypilot/client.py:466
msgid "show this message"
msgstr "vis denne meldingen"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "mislyktes i å hente verdilisten!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "timeout henting"

#: pypilot/client.py:507
msgid "missing"
msgstr "savnet"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kunne ikke importere nødvendige moduler. Glemte du å kjøre sudo "
"python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "GPSD tilkoblet"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "gpsd kunne ikke koble til"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "unntak som kobler til GPS"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "gpsd frakoblet"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "gpsd PROBE suksess"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "gpsd-sonde mislyktes"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "GPSD deaktivert"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd kunne ikke bestemme seriell overføringshastighet for enheten"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "gpsd timeout fra mangel på data"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd mottok ugyldig melding"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd fikk flagg for pipe:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "gpsd seriell sonde"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea kunne ikke analysere GPS"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea klarte ikke å analysere vind"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "unntak parsing apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "uhåndtert nmea rørstreng"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "mistet serie"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea fikk flagg for prosessrør:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "får en annen prosess tilgang til den?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "seriell enhet ble tidsavbrutt"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "kunne ikke åpnes"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "nmea server på port"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "bind mislyktes."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "lytter på port"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "for nmea-forbindelser"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "nmea server har for mange tilkoblinger"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "nmea klient mistet tilkoblingen"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "nmea sokk ikke i stikkontakter!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea kunne ikke avregistrere kontakten"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea klarte ikke å fjerne fd"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea kunne ikke fjerne adressen"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "ugyldig verdi"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "tilkoblingsfeil"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "tilkobling mislyktes"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "nmea klient tilkoblet"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "avstemningen tok for lang tid i nmea-prosessen!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "nmea bridge mistet serverforbindelse"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge mistet rør til autopilot"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge uhåndtert avstemningsflagg"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "nmea prosessløkke for sakte:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "feil rørblokk på recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "mislyktes i å rekvirere ikke-blokkerende rør!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "rør fullt"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "kan ikke sende"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "kunne ikke dekode datakontakten!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "kunne ikke kode datakontakten!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "mislyktes skrive"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ADVARSEL: Python ujson-biblioteket mislyktes, parsing vil forbruke mer CPU"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "dårlig rorkalibrering"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "dårlig servoror kalibrering"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "servoror autogain mislyktes"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "sensor funnet"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "ukjente data analysert!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "feillesing"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "fant flere enheter etter sti"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "fjerne GPS-enhet"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "ingen pyudev-modul! vil skanne USB-enheter ofte!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "suksess"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "kunne ikke registrere enheten"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "FEIL ingen tilkoblinger i klokken"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "Fjern duplikat UDP-tilkobling"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "oppretter konfigurasjonskatalog:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "kunne ikke laste"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "sikkerhetskopieringsdata mislyktes også"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "klarte ikke å skrive"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: bind mislyktes; kjører du allerede en server?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "vedvarende butikk tok for lang tid!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "maks. forbindelser nådd"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "server legge til stikkontakt"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "internt rør lukket, serveren avsluttes"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "serveruttak stengt fra spyling !!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "servokalibrering ugyldig"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "mislyktes i å åpne servo på:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "mislykket sett ikke-blokkering / eksklusivt"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "funnet"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "lasting av servokalibrering"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "ADVARSEL: bruker standard servokalibrering !!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "sondering"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "arduino servo oppdaget"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "enheten som trengs for alternativet"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "les token"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "mislyktes i å lese token"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "feilet med å"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "autodeteksjon ikke mulig"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "prøve"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "eller"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "tjenesten fjernet"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "server tapt"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "tjenestetillegg"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "server funnet"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "sonde"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "kunne ikke"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "mislyktes i å hente / analysere data fra"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "se om token er klar"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "mottatt token"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "mislyktes i å lagre token"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "feil med å be om tilgang"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "be om tilgangsadresse"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "kan ikke opprette forbindelse:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "dårlig status, avviser token"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "forbindelsen nektet"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "Koblet til"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Unntak konvertere signalk-> pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "mottatt"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "kunne ikke sende oppdateringer"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "klarte ikke å analysere meldingen:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "ugyldig opprinnelig verdi for områdeegenskap"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "ugyldig sett"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Feil ved innlasting"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "unntak i kalibrering:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "advarsel: ubehandlet melding"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilotkontroll"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Du"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "havn"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "styrbord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Kompass"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Vind"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Ekte vind"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Senter"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Omfang"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrering"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Lukk"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Kalibrering"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Båten er i vater"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Nullstille"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Justering"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Overskrift"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Koordiner"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Hav"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Båt"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "omfang"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Tonehøyde"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Rull"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Hæl"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "Justering"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Kalibreringsalder"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "Klar"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "kalibrering låst"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "accelere"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Sigma poeng"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "lokalhistorie"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "nåværende"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Kalibreringspunkter"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "kompass"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr "Trykk på hver knapp når roret er i riktig posisjon for å kalibrere."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Ror"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Tilbakestill kalibrering"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Ror er sentrert"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Ror er styrbord"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Skala"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Ror er havneserie"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Ikke lineæritet"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "rekkevidde + -"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "grader"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "ror"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "innstillinger"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "mislyktes i å laste inn pywavefront:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "ugyldige dimensjoner"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Har du lagt til pypilot_data-depotet?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "ikke funnet, teksturkompass kan ikke brukes"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Forfriske"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Tilkoblet"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Frakoblet"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "advarsel, ugyldig valgverdi spesifisert"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "pypilot Omfang"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Null"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skala +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Skala -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Offset \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Fryse"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Tid"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "ikke funnet verdier:"

#~ msgid "failed to load pilot"
#~ msgstr "mislyktes i å laste pilot"

#~ msgid "in"
#~ msgstr "i"

#~ msgid "seconds"
#~ msgstr "sekunder"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-klienten kunne ikke koble til"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "mislyktes i å opprette nmea-sokkel som vert: port"

#~ msgid "terminate calibration process"
#~ msgstr "avslutte kalibreringsprosessen"
