# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Verfügbare Piloten"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "Warnung: Sonderdatei konnte nicht geöffnet werden"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "zum Schreiben"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "kann den Wachhund nicht streicheln"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr "Warnung: Der Autopilot konnte nicht in Echtzeit verarbeitet werden"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "Server / Client läuft zu langsam"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "Sensoren laufen zu langsam"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "Die Autopilot-Routine läuft zu langsam"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "Servo läuft zu langsam"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-Bibliothek nicht erkannt, bitte installieren Sie sie"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Einstellungsdatei verwenden"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "FEHLER: Keine IMU erkannt"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEHLER: IMU-Init fehlgeschlagen, keine Trägheitsdaten verfügbar"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "Warnung, Imu-Prozess konnte nicht in Echtzeit ausgeführt werden"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "Imu-Prozess in Echtzeit gemacht"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "Einstellen der anfänglichen Kreiselvorspannung"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "Imu-Prozess konnte die Zeit nicht halten"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "IMU konnte nicht gelesen werden!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "imu rate auf rate eingestellt"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "zu hohe Kreiselvorspannung, Sensoren zurücksetzen"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "Kompass außerhalb der Reichweite, zurücksetzen"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "Warnung, Kalibrierungsprozess konnte nicht anders ausgeführt werden"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"Warnung, Kalibrierungsprozess konnte nicht im Leerlauf ausgeführt werden, "
"und Renice wurde versucht"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "Warnung, Kalibrierungsprozess konnte nicht erneut gestartet werden"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "Kalibrierung geladen, beginnend"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "Fehler beim Importieren der Importkalibrierung"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "Beschleunigungswerte ungültig"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "Überlauf in der Pypilot-UDP-Buchse"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "Überlauf in der Pypilotbuchse"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "udp-Paket konnte nicht gesendet werden"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "Pypilot-Socket konnte nicht gesendet werden"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "Socket Send hat zu lange gedauert!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "Socket-Sendefehler"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "Pypilot-Socket-Ausnahme"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"Wenn Sie auf den nicht blockierenden Python-Socket zurückgreifen, wird mehr "
"CPU verbraucht"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "Socket-Sendefehler beim Server Flush"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "Fehler beim Empfangen von Daten"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"Wissenschaftliche Bibliothek konnte nicht geladen werden, "
"Kalibrierungsaktualisierung kann nicht durchgeführt werden!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "Warnung, vorhandenen Wert registrieren:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "Konfigurationsdatei konnte nicht gelesen werden:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "Konfigurationsdatei konnte nicht geschrieben werden:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Ausnahme beim Schreiben der Konfigurationsdatei:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "ungültige Nachricht vom Server:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "Warnung, Pypilot-Client hat bereits Verbindung"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "Verbindung fehlgeschlagen zu"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "Verbindung konnte nicht hergestellt werden"

#: pypilot/client.py:460
msgid "usage"
msgstr "Verwendung"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "Stellen Sie die Host- oder IP-Adresse ein"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "Drucken Sie Informationen zu jedem Werttyp"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "kontinuierliche Uhr"

#: pypilot/client.py:466
msgid "show this message"
msgstr "zeige diese Nachricht"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "Werteliste konnte nicht abgerufen werden!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "Timeout abrufen"

#: pypilot/client.py:507
msgid "missing"
msgstr "fehlt"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot konnte die erforderlichen Module nicht importieren. Haben Sie "
"vergessen, sudo python3 setup.py install auszuführen?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "GPSD verbunden"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "GPSD konnte keine Verbindung herstellen"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "Ausnahme beim Herstellen einer Verbindung zu GPS"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "GPSD getrennt"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "gpsd PROBE Erfolg"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "GPSD-Test fehlgeschlagen"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "GPSD deaktiviert"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd konnte die serielle Baudrate des Geräts nicht ermitteln"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "GPSD-Timeout aufgrund fehlender Daten"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd hat eine ungültige Nachricht erhalten"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd hat flag für pipe:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "gpsd serielle Sonde"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea konnte GPS nicht analysieren"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea konnte den Wind nicht analysieren"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "Ausnahme Parsing apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "unbehandelte nmea Rohrschnur"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "verlorene Seriennummer"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea hat Flag für Prozessrohr erhalten:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "greift ein anderer Prozess darauf zu?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "Zeitüberschreitung des seriellen Geräts"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "Gescheitert zu öffnen"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "nmea Server am Port"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "Bindung fehlgeschlagen."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "am Hafen lauschen"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "für nmea Verbindungen"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "Der nmea-Server hat zu viele Verbindungen"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "nmea-Client Verbindung verloren"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "nmea Socke nicht in Sockeln!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea konnte die Registrierung des Sockets nicht aufheben"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea konnte fd nicht entfernen"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea konnte die Adresse nicht entfernen"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "Ungültiger Wert"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "Verbindungsfehler"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "Verbindung nicht möglich"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "nmea-Client verbunden"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "Umfrage hat im nmea-Prozess zu lange gedauert!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "nmea bridge verlor die Serververbindung"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea Brücke verlor Rohr zum Autopiloten"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "nmea Brücke unbehandelte Umfrage Flagge"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "nmea Prozessschleife zu langsam:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "Fehler Rohrblock auf recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "Nicht blockierende Pipe konnte nicht wiederhergestellt werden!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "Rohr voll"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "kann es nicht versenden"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "Daten-Socket konnte nicht dekodiert werden!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "Daten-Socket konnte nicht codiert werden!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "Schreibfehler"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"WARNUNG: Die Python-Ujson-Bibliothek ist fehlgeschlagen. Beim Parsen wird "
"mehr CPU verbraucht"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "schlechte Ruderkalibrierung"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "schlechte Servoruderruderkalibrierung"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "Servo-Ruder-Autogain fehlgeschlagen"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "Sensor gefunden"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "unbekannte Daten analysiert!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "Fehler beim Lesen"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "Weitere Geräte über den Pfad gefunden"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "GPS-Gerät entfernen"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "kein Pyudev-Modul! scannt USB-Geräte oft!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "Erfolg"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "Gerät konnte nicht aufgezeichnet werden"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "FEHLER keine Verbindungen in der Uhr"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "Entfernen Sie die doppelte udp-Verbindung"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "Konfigurationsverzeichnis erstellen:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "Laden fehlgeschlagen"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "Sicherungsdaten sind ebenfalls fehlgeschlagen"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "konnte nicht schreiben"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: Bindung fehlgeschlagen; läuft schon ein Server?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "Der dauerhafte Speicher hat zu lange gedauert!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "max Verbindungen erreicht"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "Server Socket hinzufügen"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "Interne Pipe geschlossen, Server beendet"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "Server-Socket von Flush geschlossen !!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "Servokalibrierung ungültig"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "Servo konnte nicht geöffnet werden am:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "Fehler gesetzt nicht blockierend / exklusiv"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "gefunden"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "Laden der Servokalibrierung"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "WARNUNG: Standard-Servokalibrierung verwenden !!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "Sondierung"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "Arduino Servo erkannt"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "Gerät für Option benötigt"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "Token lesen"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "Token konnte nicht gelesen werden"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "gescheitert"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "automatische Erkennung nicht möglich"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "Versuchen"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "oder"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "Service entfernt"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "Server verloren"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "Service hinzufügen"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "Server gefunden"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "Sonde"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "konnte nicht"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "Daten konnten nicht abgerufen / analysiert werden"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "Überprüfen Sie, ob das Token bereit ist"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "Token erhalten"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "Token konnte nicht gespeichert werden"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "Fehler beim Anfordern des Zugriffs"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "Zugangs-URL anfordern"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "Verbindung kann nicht hergestellt werden:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "schlechter Status, Token ablehnen"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "Verbindung abgelehnt"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "verbunden"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Ausnahme beim Konvertieren von signalk-> pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "empfangen"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "Aktualisierungen konnten nicht gesendet werden"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "Nachricht konnte nicht geparst werden:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "ungültiger Anfangswert für Bereichseigenschaft"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "ungültiger Satz"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Ladefehler"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "Ausnahme bei der Kalibrierung:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "Warnung: unbehandelte Nachricht"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilot-Steuerung"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Sie"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "N / A"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "N / A"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "N / A"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "Hafen"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "Steuerbord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Kompass"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "Geographisches Positionierungs System"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Wind"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Wahrer Wind"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Center"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Umfang"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrierung"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Schließen"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Kalibrierung"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Boot ist eben"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Zurücksetzen"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Ausrichtung"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Überschrift"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "N / A"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Koordinaten"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Meer"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Boot"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Umfang"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Tonhöhe"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Rollen"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Hacke"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "Ausrichtung"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Kalibrierungsalter"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "klar"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "Kalibrierung gesperrt"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "beschleunigen"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Sigma Punkte"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "lokale Geschichte"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "Strom"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Kalibrierungspunkte"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "Kompass"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Drücken Sie jede Taste, wenn sich das Ruder an der richtigen Position zum "
"Kalibrieren befindet."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Ruder"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Kalibrierung zurücksetzen"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Das Ruder ist zentriert"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------ ------."

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Ruder ist Steuerbord Range"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Rahmen"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Ruder ist Port Range"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Nichtlinearität"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "Bereich + -"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "Grad"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "Ruder"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "die Einstellungen"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "pywavefront konnte nicht geladen werden:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "ungültige Anzeigeabmessungen"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Haben Sie das Repository pypilot_data hinzugefügt?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "nicht gefunden, Texturkompass kann nicht verwendet werden"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Aktualisierung"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "In Verbindung gebracht"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Getrennt"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "Warnung, ungültiger Auswahlwert angegeben"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "Pypilot Scope"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Null"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Scale +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Skala -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Offset \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Einfrieren"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Zeit"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "Werte nicht gefunden:"

#~ msgid "failed to load pilot"
#~ msgstr "Pilot konnte nicht geladen werden"

#~ msgid "in"
#~ msgstr "im"

#~ msgid "seconds"
#~ msgstr "Sekunden"

#~ msgid "nmea client failed to connect to"
#~ msgstr "Der nmea-Client konnte keine Verbindung herstellen"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "Fehler beim Erstellen des nmea-Sockets als Host: Port"

#~ msgid "terminate calibration process"
#~ msgstr "Beenden Sie den Kalibrierungsprozess"
